/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package railwayreservationsystem;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ABC
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
        setIcon();
        //adminpass.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sgn_name_typed = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sgn_age_typed = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sgn_mobileno_typed = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sgn_email_typed = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sgn_state_typed = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sgn_gender_selected = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        sgn_acc_type = new javax.swing.JComboBox<>();
        adminpass = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        sgn_pwd_typed = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Railway Reservation System");

        jLabel1.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        jLabel1.setText("Sign Up");

        jLabel2.setText("Name");

        jLabel3.setText("Age");

        jLabel4.setText("Mobile No");

        jLabel5.setText("Email");

        jLabel6.setText("Password");

        jLabel7.setText("State");

        jLabel8.setText("Gender");

        sgn_gender_selected.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        sgn_gender_selected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgn_gender_selectedActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_icon.png"))); // NOI18N
        jButton2.setText("Go Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Account Type");

        sgn_acc_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Customer" }));
        sgn_acc_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgn_acc_typeActionPerformed(evt);
            }
        });

        submitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submit_icon.png"))); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(submitBtn)
                            .addComponent(sgn_name_typed)
                            .addComponent(sgn_age_typed)
                            .addComponent(sgn_mobileno_typed)
                            .addComponent(sgn_email_typed)
                            .addComponent(sgn_state_typed, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(sgn_gender_selected, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sgn_acc_type, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adminpass))
                            .addComponent(sgn_pwd_typed))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sgn_name_typed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sgn_age_typed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sgn_mobileno_typed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sgn_email_typed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sgn_pwd_typed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sgn_state_typed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sgn_gender_selected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sgn_acc_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adminpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(submitBtn)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sgn_gender_selectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgn_gender_selectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sgn_gender_selectedActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        Login lgn = new Login();
        lgn.setLocationRelativeTo(null);
        lgn.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sgn_acc_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgn_acc_typeActionPerformed
        Object selectedItem  = sgn_acc_type.getSelectedItem();
        if (selectedItem.toString().equalsIgnoreCase("Admin")) {
            adminpass.setVisible(true);
        }
        if (selectedItem.toString().equalsIgnoreCase("Customer")) {
            adminpass.setVisible(false);
        }
    }//GEN-LAST:event_sgn_acc_typeActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        
        String adminKey = "12345";
        
        String name =sgn_name_typed.getText().toString();
        String age =sgn_age_typed.getText().toString();
        String mobileNo =sgn_mobileno_typed.getText().toString();
        String email =sgn_email_typed.getText().toString();
        String password =sgn_pwd_typed.getText().toString();
        String state =sgn_state_typed.getText().toString();
        String gender =sgn_gender_selected.getSelectedItem().toString();
        String accType =sgn_acc_type.getSelectedItem().toString();
        String admpass= adminpass.getText().toString();
        int chk = 0;
        
        if (name.length()==0 || age.length()==0 || mobileNo.length()==0 || email.length()==0 || password.length()==0 || state.length()==0) {
            JOptionPane.showMessageDialog(null,"Please fill out all the fields");
        }
        
        else if (accType.equalsIgnoreCase("Admin") && admpass.length()==0) {
            JOptionPane.showMessageDialog(null,"Please type the Admin key");
        }
        
        else if (accType.equalsIgnoreCase("Admin") && !admpass.equals("12345")) {
            JOptionPane.showMessageDialog(null,"Invalid Admin key");
        }
        
        else if (!email.contains("@") || !email.contains(".com")) {
            JOptionPane.showMessageDialog(null,"Invalid Email");
        }
        
        /*else if (Integer.parseInt(age)>0 && Integer.parseInt(age)<=120) {
            JOptionPane.showMessageDialog(null,"Invalid Age");
        }*/
        
        else {
            DB_Connection.DB_Connection obj_DB_Connection=new DB_Connection.DB_Connection();
            Connection connection=obj_DB_Connection.get_connection();
            PreparedStatement ps=null;
            
            try {
                String query="SELECT U_Email FROM User";
                ps=connection.prepareStatement(query);
                ResultSet rs=ps.executeQuery();
                while (rs.next()) {
                    String check =rs.getString("U_Email");
                    if (check.equals(email)) {
                        JOptionPane.showMessageDialog(null,"Email already exists");
                        chk=1;
                    }
                }
                
                if (chk==0) {
                    String data = "INSERT INTO User (U_Name,U_Gender,U_Age,U_Mobile_No,U_Email,U_Password,State,Account_Type)"+
                        "VALUES(?,?,?,?,?,?,?,?)";
                
                PreparedStatement preparedStatement = connection.prepareStatement(data);
                preparedStatement.setString(1, ""+name);
                preparedStatement.setString(2, ""+gender);
                preparedStatement.setString(3, ""+age);
                preparedStatement.setString(4, ""+mobileNo);
                preparedStatement.setString(5, ""+email);
                preparedStatement.setString(6, ""+password);
                preparedStatement.setString(7, ""+state);
                preparedStatement.setString(8, ""+accType);
                preparedStatement.executeUpdate();
                
                JOptionPane.showMessageDialog(null,"Your Account has been created");
                }
                
            }catch(Exception e) {
                JOptionPane.showMessageDialog(null,""+e);
            }
        }
        
    }//GEN-LAST:event_submitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminpass;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> sgn_acc_type;
    private javax.swing.JTextField sgn_age_typed;
    private javax.swing.JTextField sgn_email_typed;
    private javax.swing.JComboBox<String> sgn_gender_selected;
    private javax.swing.JTextField sgn_mobileno_typed;
    private javax.swing.JTextField sgn_name_typed;
    private javax.swing.JPasswordField sgn_pwd_typed;
    private javax.swing.JTextField sgn_state_typed;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/app_icon.png")));
    }
}
